-- Script to create production databases for 

-- IBM Control Center. 

-- The db user that creates the database automatically inherits the 

-- database administration privilege.

-- Edit this script and replace @DBNAME@ with your database name. 


-- 
CREATE DATABASE @DBNAME@ 

AUTOMATIC STORAGE YES 

USING CODESET UTF-8 TERRITORY DEFAULT 

COLLATE USING SYSTEM PAGESIZE 32768;


CONNECT TO @DBNAME@;

CREATE BUFFERPOOL @DBNAME@_04KBP IMMEDIATE SIZE AUTOMATIC PAGESIZE 4K;

CREATE BUFFERPOOL @DBNAME@_08KBP IMMEDIATE SIZE AUTOMATIC PAGESIZE 8K;

CREATE BUFFERPOOL @DBNAME@_16KBP IMMEDIATE SIZE AUTOMATIC PAGESIZE 16K;

CONNECT RESET;


CONNECT TO @DBNAME@;

CREATE  USER TEMPORARY  TABLESPACE SCCUSERTMP PAGESIZE 32K  BUFFERPOOL  IBMDEFAULTBP; 

CREATE REGULAR TABLESPACE TS_REG04_@DBNAME@  PAGESIZE 4K   BUFFERPOOL  @DBNAME@_04KBP PREFETCHSIZE AUTOMATIC;
 
CREATE REGULAR TABLESPACE TS_REG08_@DBNAME@  PAGESIZE 8K   BUFFERPOOL  @DBNAME@_08KBP PREFETCHSIZE AUTOMATIC;

CREATE REGULAR TABLESPACE TS_REG16_@DBNAME@  PAGESIZE 16K  BUFFERPOOL  @DBNAME@_16KBP PREFETCHSIZE AUTOMATIC;

CONNECT RESET;
